version: '3'
services:
  be:
    build:
      context: ./be
      dockerfile: ./.docker/Dockerfile
      args:
        - PORT=8080
        - MONGODB_URL=mongodb://mongodb:27017/kse
    ports:
      - 127.0.0.1:9101:8080
    image: kse/be
    container_name: be
    networks:
      - kse
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - "/usr/local/kse/db:/data/db"
    ports:
      - "27017:27017"
    container_name: mongodb
    networks:
      - kse
  fe:
    build:
      context: ./fe
      dockerfile: ./.docker/Dockerfile
    ports:
      - 127.0.0.1:9100:80
    image: kse/fe
    container_name: fe
networks:
  kse:
    driver: bridge
