version: '3'
services:
  dev:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - DATABASE_NAME="kse"
    ports:
      - "5432:5432"
  